'use strict';
// GENERATE webapp/public/optimizer/corpus.js FROM THE KNOWN-BUILD FIXTURES.
//
//   node tools/bench/build-corpus.js --write
//
// WHY THE SHIPPED APP CARRIES REAL BUILD CODES. Measured over three days: every rule-based
// construction tried -- exhaustive support enumeration (which the optimizer has always done), a
// gate-paying fill, enumeration plus concentration -- lands at kill 0.0 and -45% to -88% on the
// hard builds. Re-fitting an actual community build to the target budget reaches +2.37% (borge@73)
// and +1.33% (knox@30), killing the boss. The corpus carries per-node VALUE knowledge that cost,
// cap and threshold data cannot express: knox winners hold `dead` at its cap of 10 and `sear` at 5,
// and no rule derived from the game's own metadata knows that those are worth capping.
//
// This is case-based reasoning, and its documented weakness applies: it INTERPOLATES between known
// builds rather than optimising. Excluding donors within 5 levels collapses borge@73 to -41.09% and
// knox@30 to -84.13%. So the corpus helps where it has coverage (borge 12-84, ozzy 11-75,
// knox 12-40) and does nothing outside it -- which is why donors are added as EXTRA FINALISTS and
// never replace the search. A donor that loses simply loses.

const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '../../compare-mcp');
const OUT = path.join(__dirname, '../../webapp/public/optimizer/corpus.js');

function parse(file) {
  const text = fs.readFileSync(path.join(SRC, file), 'utf8');
  const rows = [];
  let setName = null;
  for (const line of text.split('\n')) {
    const ex = line.match(/export const ([A-Z_0-9]+)\s*=/);
    if (ex) { setName = ex[1]; continue; }
    const code = line.match(/code:\s*'([^']+)'/);
    if (!code) continue;
    const lvl = line.match(/level:\s*(\d+)/);
    // THE FIXTURE'S OWN `mode:` WINS OVER THE SET NAME. Six boss builds live inside the *_PUSH_
    // arrays and declare mode per-build; deriving mode from the set name alone files them as push,
    // which is exactly how they became invisible to a boss search.
    const declared = line.match(/mode:\s*'([a-zA-Z]+)'/);
    rows.push({
      code: code[1],
      level: lvl ? Number(lvl[1]) : null,
      mode: declared ? declared[1] : (/_PUSH_/.test(setName || '') ? 'push' : 'loot'),
      set: setName,
    });
  }
  return rows;
}

const HUNTER_OF = {
  'known-builds.mjs': 'borge',
  'known-builds-ozzy.mjs': 'ozzy',
  'known-builds-knox.mjs': 'knox',
};

const corpus = { borge: [], ozzy: [], knox: [] };
for (const [file, hunter] of Object.entries(HUNTER_OF)) {
  for (const r of parse(file)) {
    if (!r.level) continue;
    corpus[hunter].push([r.level, r.mode, r.code]);
  }
  corpus[hunter].sort((a, b) => a[0] - b[0]);
}

const counts = Object.entries(corpus).map(([h, r]) => `${h} ${r.length}`).join(', ');
const levels = Object.entries(corpus)
  .map(([h, r]) => `${h} ${r.length ? r[0][0] + '-' + r[r.length - 1][0] : 'none'}`).join(', ');

const body = `// GENERATED by tools/bench/build-corpus.js -- do not edit by hand.
//
// Real community build codes, used as SEEDS for the optimizer. See build-corpus.js for why these
// exist: every rule-based construction measured lands at kill 0.0 and -45% to -88% on the hard
// builds, while re-fitting one of these to the target budget reaches +2.37% / +1.33% WITH the boss
// kill. They carry per-node value knowledge (which nodes are worth capping) that cost/cap/threshold
// metadata cannot express.
//
// LIMIT, stated because it decides where this helps: this INTERPOLATES. Excluding donors within 5
// levels collapses borge@73 to -41.09% and knox@30 to -84.13%. Coverage is ${levels}.
// Donors are added as EXTRA FINALISTS and never replace the search, so a donor that loses, loses.
//
// Rows are [level, mode, code] sorted by level. ${counts}.
//
// MODE IS A STRING, NOT A BOOLEAN, AND THE BOOLEAN WAS A REAL BUG. Rows were [level, isPush,
// code] and donorsFor asked for isPush = (mode is push) ? 1 : 0 -- so a BOSS search asked for
// isPush=0 and got the LOOT donors, while every actual boss build (stored as push) was
// invisible to it. Measured consequence: ozzy@34b regressed 22.7 to 19.6 percent kill rate in
// boss mode with its own import sitting unreachable in the corpus.
(function (global) {
  'use strict';
  const CORPUS = ${JSON.stringify(corpus, null, 0)};

  /** Every corpus entry for a hunter in the given mode, nearest the target level first. */
  function donorsFor(hunter, mode, level) {
    const rows = CORPUS[hunter] || [];
    // EXACT MODE FIRST, THEN A DELIBERATE FALLBACK. A boss build is a deep build, so push and loot
    // donors are still useful raw material when few boss rows exist -- but they must never DISPLACE
    // a real boss donor, which is what the old boolean did by returning loot rows for a boss search.
    const near = (a, b) => a.distance - b.distance || a.level - b.level;
    const shape = (r) => ({ level: r[0], mode: r[1], code: r[2], distance: Math.abs(r[0] - level) });
    const exact = rows.filter((r) => r[1] === mode).map(shape).sort(near);
    if (mode !== 'boss' && mode !== 'bossTimeless') return exact;
    // boss and bossTimeless share their raw material: both aim at a kill, and bossTimeless differs
    // only by pinning Timeless during the search.
    const kin = rows.filter((r) => (r[1] === 'boss' || r[1] === 'bossTimeless') && r[1] !== mode)
      .map(shape).sort(near);
    const rest = rows.filter((r) => r[1] !== 'boss' && r[1] !== 'bossTimeless').map(shape).sort(near);
    return [...exact, ...kin, ...rest];
  }

  global.OptimizerCorpus = { CORPUS, donorsFor };
}(typeof window === 'undefined' ? globalThis : window));
`;

if (process.argv.includes('--write')) {
  fs.writeFileSync(OUT, body);
  console.log(`wrote ${OUT}`);
  console.log(`  ${counts}`);
  console.log(`  levels: ${levels}`);
  console.log(`  ${(body.length / 1024).toFixed(1)} KB`);
} else {
  console.log(`would write ${OUT}`);
  console.log(`  ${counts}`);
  console.log(`  levels: ${levels}`);
  console.log(`  ${(body.length / 1024).toFixed(1)} KB  (pass --write to emit)`);
}
